### ISSUE TITLE
move remaining parts of configuration from `config.yaml` to `docker-bake.hcl`

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/workflows#21]
https://github.com/DARMA-tasking/workflows/pull/19 moved majority of configuration for building docker images into `docker-bake.hcl` (including compilers setup, packages, `PATH_PREFIX`). Setup scripts generated from `setup-template.sh` now only do dependencies installation from `scripts/deps`. Relevant sample:
```yaml
     deps:
       cmake: ['3.23.4']
       doxygen: ['1.8.16']
       mpich: { env: { CC: gcc-9, CXX: g++-9 }, args: [ '4.0.2', '-j4' ] }
```
Move the dependencies into `docker-bake.hcl` to get closer to removing `config.yaml`, `build-setup.py` and relying on `docker-bake.hcl` as a single source of truth.

Note: `config.yaml` is still necessary for `build-matrix.py` script, consider migrating this to using bake in a separate issue. In the end, adding a new build should be as simple as adding following snippet in `docker-bake.hcl`:
```
      {
        compiler = "gcc-12"
        extra_packages = "gcovr lcov gfortran-12"
        fc="gfortran-12"
        variant = "zoltan"
      },
```
